### PR TITLE
Add categories site webservices and small fixes

### PR DESCRIPTION
**Pull request by fastslack**

### CODE REVIEW

**Comment by wilsonge** [comment]
This is awesome! Can you PR the categories webservice into the main repo tho please. Then I'll merge the component stuff you've PR'd here

**Comment by fastslack** [comment]
Of course. Remember to fix the media path. https://github.com/wilsonge/webservices/pull/1/files#diff-9be54216bc8b6035fbe20386f1f2fa04L124

I'm doing an extensive test now, there are lot of things to fix into component. I ll made another PR soon

**Comment by wilsonge** [comment]
Yeah I know things like the published buttons don't work. But like we need to do a full rework of the component to stop using Legacy MVC - this is just a hacky fix so people can see how things are supposed to work

**Comment by wilsonge** [comment]
I've merged in the changes to the helper file :)

**Pull request closed without merging**
